force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Object to store Country information.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/CountryISOCode2__c.field-meta.xml
<CustomField>
    <fullName>CountryISOCode2__c</fullName>
    <description>Store Country ISO Code 2</description>
    <label>CountryISOCode2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/CountryISOCode3__c.field-meta.xml
<CustomField>
    <fullName>CountryISOCode3__c</fullName>
    <description>Store Country ISO Code 3</description>
    <label>CountryISOCode3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryISOCode2__c.field-meta.xml
<CustomField>
    <fullName>CountryISOCode2__c</fullName>
    <description>Store the country ISO code 2.</description>
    <label>CountryISOCode2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryISOCode3__c.field-meta.xml
<CustomField>
    <fullName>CountryISOCode3__c</fullName>
    <description>Stores Country ISO code 3.</description>
    <label>CountryISOCode3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <label>CountryName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/regionalBlocs__c.field-meta.xml
<CustomField>
    <fullName>regionalBlocs__c</fullName>
    <label>regionalBlocs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandlerTest.cls
@IsTest
public class LeadTriggerHandlerTest {

    @IsTest
    static void testHandleAfterInsert() {
        // Create test data
        Country__c country = new Country__c(Name='United States of America', CountryISOCode2__c='US', CountryISOCode3__c='USA', Capital__c='Washington, D.C.', Region__c='Americas', Subregion__c='', RegionalBlocs__c='');
        insert country;
        Country__c c1=[Select Id, Name__c, CountryISOCode2__c, CountryISOCode3__c, Capital__c, Region__c, Subregion__c, RegionalBlocs__c From Country__c Where CountryISOCode2__c='US'];
        List<Lead> leads = new List<Lead>{
            new Lead(FirstName='Test', LastName='Lead', Company='Test Company', CountryISOCode2__c=country.CountryISOCode2__c)
        };
            
        
        // Call the trigger handler method
        Test.startTest();
        Insert leads;
        Test.stopTest();
        
        // Verify that the lead country information was updated
        Lead lead = [SELECT Country__c, CountryName__c, CountryISOCode2__c, CountryISOCode3__c, Capital__c, Region__c, Subregion__c, RegionalBlocs__c FROM Lead WHERE Id = :leads[0].Id];
        System.assertEquals('United States of America', lead.CountryName__c);
        System.assertEquals('US', lead.CountryISOCode2__c);
        System.assertEquals('USA', lead.CountryISOCode3__c);
        System.assertEquals('Washington, D.C.', lead.Capital__c);
        System.assertEquals('Americas', lead.Region__c);
        System.assertEquals(null, lead.Subregion__c);
        System.assertEquals(null, lead.RegionalBlocs__c);
    }

}